spring:
  main:
    web-application-type: none
  application:
    name: aggregator
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    non-secure-port: ${server.port}
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10