services:
  ewm-db:
    container_name: ewm-db
    image: postgres:16.1
    ports:
      - "8432:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15

  stats-db:
    container_name: stats-db
    image: postgres:16.1
    ports:
      - "8433:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 10s
      retries: 15