services:
  ewm-db:
    container_name: ewm-db
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  stats-db:
    container_name: stats-db
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345