CREATE TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(500),
    text VARCHAR(500),
    name VARCHAR(250),
    created TIMESTAMP,
    creator_id BIGINT,
    event_id BIGINT,
    state VARCHAR
);