CREATE TABLE IF NOT EXISTS compilation_event (
    compilation_id BIGINT,
    event_id BIGINT,
    PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE views (
    id SERIAL PRIMARY KEY,
    event_id BIGINT NOT NULL,
    ip VARCHAR(45) NOT NULL,
    CONSTRAINT unique_event_ip UNIQUE (event_id, ip)
);

CREATE TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(500),
    text VARCHAR(500),
    name VARCHAR(250),
    created TIMESTAMP,
    creator_id BIGINT,
    event_id BIGINT,
    state VARCHAR
);