logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG
    org.springframework.web.server: DEBUG
server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: main_service_all
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/**
