server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: user_service_admin
          uri: lb://USER-SERVICE
          predicates:
            - Path=/admin/users/**


        - id: main_service_all
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/**
